require 'tupp'
require 'tupp/identifier'
require 'tupp/identifier/doi'
require 'tupp/reference'
require 'tupp/reference/event'
require 'tupp/reference/event/conference'
require 'tupp/reference/person'
require 'tupp/reference/organisation'
require 'tupp/reference/publication'
require 'tupp/reference/publication/book'
require 'tupp/reference/publication/conference_paper'
require 'tupp/reference/publication/journal_issue'
require 'tupp/reference/publication/journal_article'
require 'tupp/reference/publication/thesis'

