version: '3'

services:
  mq:
    ports: 
      - "15673:15672"

  # Stubbing service for datastore
  datastore:
    image: gitlab.cvt.dk:5001/dtulibrary/datastore_stub
    environment:
      RABBITMQ_URL: 'amqp://guest:guest@mq:5672/%2f'
    depends_on:
      - mq

  harvester:
    build:
      context: .
      dockerfile: harvester/Dockerfile
    environment:
      RABBITMQ_URL: 'amqp://guest:guest@mq:5672/%2f'
